version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=database 
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=P@ssw0rd123
      - DB_NAME=ProyectoKn
      - JWT_SECRET=clave_secreta14
    depends_on:
      database:
        condition: service_healthy  # Espera hasta que la DB esté lista

  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd123
      POSTGRES_DB: ProyectoKn
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:  # Agrega un chequeo de salud para asegurarse de que PostgreSQL está listo
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  pg_data:
